apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-demo
  template:
    metadata:
      labels:
        app: aiops-demo
    spec:
      containers:
        - name: aiops-demo
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
