#!/usr/bin/env python3

import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

NAMESPACE = "capstone-aiops-demo"
SERVICE = "aiops-demo"
DEPLOYMENT = "aiops-demo"
GITOPS_FILE = Path("apps/capstone-aiops-demo/base/service.yaml")
BRANCH = "aiops/fix-aiops-demo-service-selector"

def run(cmd, capture=True, check=True):
    print(f"\n$ {' '.join(cmd)}")
    result = subprocess.run(
        cmd,
        text=True,
        capture_output=capture,
        check=False,
    )

    if capture and result.stdout:
        print(result.stdout.strip())

    if capture and result.stderr:
        print(result.stderr.strip())

    if check and result.returncode != 0:
        raise SystemExit(result.returncode)

    return result.stdout.strip() if capture else ""

def kubectl_json(args):
    output = run(["kubectl", *args, "-o", "json"])
    return json.loads(output)

def main():
    print("AIOps service selector remediation started")
    print(f"Namespace: {NAMESPACE}")
    print(f"Service: {SERVICE}")
    print(f"Deployment: {DEPLOYMENT}")

    service = kubectl_json(["get", "svc", SERVICE, "-n", NAMESPACE])
    deployment = kubectl_json(["get", "deployment", DEPLOYMENT, "-n", NAMESPACE])
    endpoints = kubectl_json(["get", "endpoints", SERVICE, "-n", NAMESPACE])

    selector = service.get("spec", {}).get("selector", {})
    pod_template_labels = (
        deployment
        .get("spec", {})
        .get("template", {})
        .get("metadata", {})
        .get("labels", {})
    )
    subsets = endpoints.get("subsets")

    print("\nEvidence summary")
    print(f"Service selector: {selector}")
    print(f"Deployment pod template labels: {pod_template_labels}")
    print(f"Endpoint subsets: {subsets}")

    if subsets:
        print("Service already has endpoints. No remediation PR needed.")
        return

    wrong_app = selector.get("app")
    correct_app = pod_template_labels.get("app")

    if not wrong_app or not correct_app:
        raise SystemExit("Could not determine Service app selector or Deployment app label.")

    if wrong_app == correct_app:
        print("Service selector already matches pod label. No remediation PR needed.")
        return

    print("\nRoot cause")
    print(f"Service selector app={wrong_app} does not match pod label app={correct_app}")

    if not GITOPS_FILE.exists():
        raise SystemExit(f"GitOps file not found: {GITOPS_FILE}")

    run(["git", "checkout", "main"])
    run(["git", "pull"])
    run(["git", "checkout", "-B", BRANCH])

    text = GITOPS_FILE.read_text()

    old_line = f"    app: {wrong_app}"
    new_line = f"    app: {correct_app}"

    if old_line not in text:
        raise SystemExit(f"Expected selector line not found in {GITOPS_FILE}: {old_line}")

    GITOPS_FILE.write_text(text.replace(old_line, new_line, 1))

    print("\nPatched GitOps file")
    print(f"{GITOPS_FILE}: {old_line.strip()} -> {new_line.strip()}")

    run(["git", "diff", "--", str(GITOPS_FILE)])

    run(["git", "add", str(GITOPS_FILE)])

    commit_result = subprocess.run(
        ["git", "commit", "-m", "AIOps fix aiops-demo service selector"],
        text=True,
        capture_output=True,
        check=False,
    )

    print(commit_result.stdout.strip())
    print(commit_result.stderr.strip())

    if commit_result.returncode != 0:
        print("No commit created. The branch may already contain this fix.")
        return

    run(["git", "push", "-u", "origin", BRANCH, "--force"])

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    pr_body = f"""## AIOps remediation: Service has no endpoints

This PR was generated by an AIOps remediation script for the isolated capstone AIOps demo app.

### Incident

Service `{SERVICE}` in namespace `{NAMESPACE}` has no endpoints.

### Evidence

- Service selector: `app={wrong_app}`
- Deployment pod label: `app={correct_app}`
- Endpoint subsets: `{subsets}`
- Generated at: `{timestamp}`

### Root cause

The Service selector does not match the pod labels, so Kubernetes cannot attach pods as Service endpoints.

### Fix

Update the Service selector from:

    app: {wrong_app}

to:

    app: {correct_app}

### Safety

This is a low-risk GitOps manifest fix for an isolated demo namespace.

It does not modify the cluster directly. Argo CD will apply the change after human review and merge.
"""

    body_file = Path("/tmp/aiops-service-selector-pr-body.md")
    body_file.write_text(pr_body)

    run([
        "gh", "pr", "create",
        "--title", "AIOps fix aiops-demo service selector",
        "--body-file", str(body_file),
        "--base", "main",
        "--head", BRANCH,
    ], check=False)

    print("\nAIOps remediation PR flow completed")

if __name__ == "__main__":
    main()
